### ISSUE TITLE
Unity 2019.3.0a12 (最新版)で動かない

### ISSUE THREAD

**Issue by qoopen0815** [WRS-TNK/unity_ros#1]
去年の進捗を確認したいのですが、READMEのUnityでの作業を進めていくと、
手順３「plojectビューにあるAssetsフォルダの直下にMeshシーンがあるのでopen」にて、Mesh_test.unityがopenできません。（以下）

![image](https://user-images.githubusercontent.com/26988372/63764132-aa1a5900-c8b5-11e9-822b-87e68742fb62.png)

コンソールに表示されているエラーログは次の通りです。

![image](https://user-images.githubusercontent.com/26988372/63764397-3af13480-c8b6-11e9-86ba-2ab0894bf653.png)

```
Component of type GUI Layer is no longer available in Unity. References to it will be removed!
```
```
Component could not be loaded when loading game object. Cleaning up!
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by Keishirou** [comment]
2点ほど確認していただきたいです．
・このプロジェクトはUnity2017.4.4f1で作成しているので，可能であれば2017台にバージョンを落としてもらえるとコンパイルできると思います．
・おそらくUnityPackageから開いてもらったと思うのですが，それが最新版ではありませんでした．先ほど最新版に更新したので，それをImportしなおしてもらうとMeshという名前のSceneがAssets内にあると思います．そちらでもう一度確認してもらえないでしょうか．

また，ReadMeの最後に書きました以下の文章も参考にお願いします．

> *新しいProjectを作った場合，一つ設定をいじる必要があります
1.上部についてるメニューからEdit > Project Settings > PlayerをOpen
2.Inspectorビューに設定画面が出てくるのでOther Settings > Configurationを見る
3.Scripting Runtime Versionが .Net 4.x Equivalent　になっていれば大丈夫


よろしくお願いします．

**Comment by qoopen0815** [comment]
さっそくの対応ありがとうございます。

![image](https://user-images.githubusercontent.com/26988372/63775109-333d8a00-c8ce-11e9-8d68-81acef6fad8c.png)

更新いただいた内容でREADMEの最後まで通すことができました。
通した結果「Connected to RosBridge」と表示され、Ubuntu-PCと接続ができることが無事に確認できました。

しかし、起動すると兵士が出てくるのを想像していたのですが、現在はworldに何も表示されません。何か対応策はありませんか？

**Comment by Keishirou** [comment]
よかったです！
兵士の生成はSubscribeに成功したときに行っているので，PCLをPublishしてもらうと出てくると思います．
仕様としては，PCLの位置情報を全てカバーできる大きさの透明な床を生成し，その上に兵士を乗せるようになっています．

**Comment by qoopen0815** [comment]
![image](https://user-images.githubusercontent.com/26988372/64145019-f9323200-ce51-11e9-9a05-8395a6451d03.png)

unity側でpointcloudをsubscribeできました！
これで去年までの進捗を確認できました。ありがとうございました！

クローズします。
